use serde::{Deserialize, Serialize};
use std::process::{Command, Stdio};
use std::io::{BufReader, BufRead};
use tauri::{AppHandle, Emitter};
use std::path::PathBuf;

#[derive(Serialize, Deserialize, Debug)]
pub struct PredictArgs {
    sex: String,
    age: String,
    height: String,
    weight: String,
    r_clav_len: String,
    r_hum_len: String,
    r_hum_epi_width: String,
    anthro_path: String,
    ssm_path: String,
    out_path: String,
}

#[tauri::command]
async fn run_prediction(app: AppHandle, args: PredictArgs) -> Result<String, String> {
    let json_args = serde_json::to_string(&args).map_err(|e| e.to_string())?;

    app.emit("progress-status", "Initializing Conda Environment...").unwrap_or(());

    let base_dir = std::env::current_dir().unwrap_or(PathBuf::from("."));
    let script_path = base_dir.join("../../scripts/predict_headless.py");
    let bones_path = base_dir.join("../public/bones.json");
    
    let script_str = script_path.to_string_lossy().to_string();

    let mut child = Command::new("cmd")
        .args(["/c", "conda", "run", "-n", "thmd2", "python", &script_str, &json_args])
        .stdout(Stdio::piped())
        .stderr(Stdio::piped())
        .spawn()
        .map_err(|e| format!("Failed to spawn cmd/conda: {}", e))?;

    let stdout = child.stdout.take().unwrap();
    let reader = BufReader::new(stdout);
    
    for line in reader.lines() {
        if let Ok(l) = line {
            println!("PYTHON OUTPUT: {}", l);
            app.emit("progress-status", l).unwrap_or(());
        }
    }

    let output = child.wait_with_output().map_err(|e| e.to_string())?;
    if output.status.success() {
        // Read the generated bones.json and return it to bypass Vite cache
        let bones_json = std::fs::read_to_string(&bones_path)
            .map_err(|e| format!("Failed to read bones.json at {:?}: {}", bones_path, e))?;
        Ok(bones_json)
    } else {
        let err = String::from_utf8_lossy(&output.stderr);
        Err(err.to_string())
    }
}

#[derive(Serialize, Deserialize, Debug)]
pub struct PatientData {
    sex: String,
    age: String,
    height: String,
    weight: String,
}

#[derive(Serialize, Deserialize, Debug)]
pub struct JointCoords {
    sc_abduction: f64,
    sc_elevation: f64,
    sc_upward: f64,
    ac_internal: f64,
    ac_upward: f64,
    ac_posterior: f64,
    gh_flexion: f64,
    gh_abduction: f64,
    gh_internal: f64,
}

#[derive(Serialize, Deserialize, Debug)]
pub struct RefinementReportArgs {
    out_path: String,
    patient: PatientData,
    right_st: JointCoords,
    left_st: JointCoords,
}

#[tauri::command]
async fn save_refinement_report(args: RefinementReportArgs) -> Result<String, String> {
    let mut path = PathBuf::from(&args.out_path);
    // If output is a .ply file, change extension to .md
    if path.extension().and_then(|s| s.to_str()) == Some("ply") {
        path.set_extension("md");
    } else {
        path.push("refinement_report.md");
    }

    let report = format!(
        "# Shoulder Refinement Report\n\n\
         ## Patient Information\n\
         - **Sex**: {}\n\
         - **Age**: {} years\n\
         - **Height**: {} cm\n\
         - **Weight**: {} kg\n\n\
         ## Refined Shoulder Kinematics (ISB)\n\n\
         ### Right Shoulder\n\
         - **SC**: Abduction: {:.2}°, Elevation: {:.2}°, Upward Rot: {:.2}°\n\
         - **AC**: Internal Rot: {:.2}°, Upward Rot: {:.2}°, Posterior Tilt: {:.2}°\n\
         - **GH**: Flexion: {:.2}°, Abduction: {:.2}°, Internal Rot: {:.2}°\n\n\
         ### Left Shoulder\n\
         - **SC**: Abduction: {:.2}°, Elevation: {:.2}°, Upward Rot: {:.2}°\n\
         - **AC**: Internal Rot: {:.2}°, Upward Rot: {:.2}°, Posterior Tilt: {:.2}°\n\
         - **GH**: Flexion: {:.2}°, Abduction: {:.2}°, Internal Rot: {:.2}°\n\n\
         *Generated by Shoulder Predictor ROI (Integrated Optimizer)*",
        args.patient.sex, args.patient.age, args.patient.height, args.patient.weight,
        args.right_st.sc_abduction, args.right_st.sc_elevation, args.right_st.sc_upward,
        args.right_st.ac_internal, args.right_st.ac_upward, args.right_st.ac_posterior,
        args.right_st.gh_flexion, args.right_st.gh_abduction, args.right_st.gh_internal,
        args.left_st.sc_abduction, args.left_st.sc_elevation, args.left_st.sc_upward,
        args.left_st.ac_internal, args.left_st.ac_upward, args.left_st.ac_posterior,
        args.left_st.gh_flexion, args.left_st.gh_abduction, args.left_st.gh_internal
    );

    std::fs::write(&path, report)
        .map_err(|e| format!("Failed to write report to {:?}: {}", path, e))?;

    Ok(format!("Report saved to {:?}", path))
}

#[cfg_attr(mobile, tauri::mobile_entry_point)]
pub fn run() {
    tauri::Builder::default()
        .plugin(tauri_plugin_opener::init())
        .invoke_handler(tauri::generate_handler![run_prediction, save_refinement_report])
        .run(tauri::generate_context!())
        .expect("error while running tauri application");
}
