use serde::{Deserialize, Serialize};
use std::process::{Command, Stdio};
use std::io::{BufReader, BufRead};
use tauri::{AppHandle, Emitter};
use std::path::PathBuf;

#[derive(Serialize, Deserialize, Debug)]
pub struct PredictArgs {
    sex: String,
    age: String,
    height: String,
    weight: String,
    r_clav_len: String,
    r_hum_len: String,
    r_hum_epi_width: String,
    anthro_path: String,
    ssm_path: String,
    out_path: String,
}

#[tauri::command]
async fn run_prediction(app: AppHandle, args: PredictArgs) -> Result<String, String> {
    let json_args = serde_json::to_string(&args).map_err(|e| e.to_string())?;

    app.emit("progress-status", "Initializing Conda Environment...").unwrap_or(());

    // Resolve python script relative to current directory. Tauri runs from TauriGUI/src-tauri usually,
    // wait! tauri dev runs from `TauriGUI`. So `../predict_headless.py` should hit the parent `Source/` dir.
    // Let's use absolute relative pathing logic:
    let script_path = std::env::current_dir()
        .unwrap_or(PathBuf::from("."))
        .join("../scripts/predict_headless.py");
    
    let script_str = script_path.to_string_lossy().to_string();

    let mut child = Command::new("cmd")
        .args(["/c", "conda", "run", "-n", "thmd2", "python", &script_str, &json_args])
        // .current_dir("../") // just in case
        .stdout(Stdio::piped())
        .stderr(Stdio::piped())
        .spawn()
        .map_err(|e| format!("Failed to spawn cmd/conda: {}", e))?;

    let stdout = child.stdout.take().unwrap();
    let reader = BufReader::new(stdout);
    
    // Read stdout line by line
    for line in reader.lines() {
        if let Ok(l) = line {
            println!("PYTHON OUTPUT: {}", l);
            app.emit("progress-status", l).unwrap_or(());
        }
    }

    let output = child.wait_with_output().map_err(|e| e.to_string())?;
    if output.status.success() {
        Ok("Prediction Complete!".to_string())
    } else {
        let err = String::from_utf8_lossy(&output.stderr);
        Err(err.to_string())
    }
}

#[derive(Serialize, Deserialize, Debug)]
pub struct PatientData {
    sex: String,
    age: String,
    height: String,
    weight: String,
}

#[derive(Serialize, Deserialize, Debug)]
pub struct STCoords {
    abduction: f64,
    elevation: f64,
    upward: f64,
    winging: f64,
}

#[derive(Serialize, Deserialize, Debug)]
pub struct RefinementReportArgs {
    out_path: String,
    patient: PatientData,
    right_st: STCoords,
    left_st: STCoords,
}

#[tauri::command]
async fn save_refinement_report(args: RefinementReportArgs) -> Result<String, String> {
    let mut path = PathBuf::from(&args.out_path);
    // If output is a .ply file, change extension to .md
    if path.extension().and_then(|s| s.to_str()) == Some("ply") {
        path.set_extension("md");
    } else {
        path.push("refinement_report.md");
    }

    let report = format!(
        "# Shoulder Refinement Report\n\n\
         ## Patient Information\n\
         - **Sex**: {}\n\
         - **Age**: {} years\n\
         - **Height**: {} cm\n\
         - **Weight**: {} kg\n\n\
         ## Refined Scapulothoracic Kinematics\n\n\
         ### Right Shoulder\n\
         - **Abduction/Protraction**: {:.2}°\n\
         - **Elevation**: {:.2}°\n\
         - **Upward Rotation**: {:.2}°\n\
         - **Winging**: {:.2}°\n\n\
         ### Left Shoulder\n\
         - **Abduction/Protraction**: {:.2}°\n\
         - **Elevation**: {:.2}°\n\
         - **Upward Rotation**: {:.2}°\n\
         - **Winging**: {:.2}°\n\n\
         *Generated by Shoulder Predictor ROI (Integrated Optimizer)*",
        args.patient.sex, args.patient.age, args.patient.height, args.patient.weight,
        args.right_st.abduction, args.right_st.elevation, args.right_st.upward, args.right_st.winging,
        args.left_st.abduction, args.left_st.elevation, args.left_st.upward, args.left_st.winging
    );

    std::fs::write(&path, report)
        .map_err(|e| format!("Failed to write report to {:?}: {}", path, e))?;

    Ok(format!("Report saved to {:?}", path))
}

#[cfg_attr(mobile, tauri::mobile_entry_point)]
pub fn run() {
    tauri::Builder::default()
        .plugin(tauri_plugin_opener::init())
        .invoke_handler(tauri::generate_handler![run_prediction, save_refinement_report])
        .run(tauri::generate_context!())
        .expect("error while running tauri application");
}
